### PR TITLE
Fix warnings for boundary.circle.radius

### LINKED ISSUE #915: Remove coarse reverse boundary.circle.radius warning
Currently all reverse requests that are either explicitly coarse or end up falling back to coarse return a warning of `boundary.circle.radius is not applicable for coarse reverse`.  Due to how the sanitizers work, `boundary.circle.radius` is set to a default if not supplied so by the time the coarse reverse controller runs, it doesn't know that value was explicitly supplied by the user or is a default.  Figure out a way to only add the warning `boundary.circle.radius` was explicitly passed by the user.

### PR DESCRIPTION
**Pull request by tigerlily-he**
Coarse reverse searches should no longer warn about `boundary.circle.radius` not being applicable. Fixes #915. This warning used to occur because if the property was undefined, the default value (1 km) would get applied in the `_geo_reverse` sanitizer. By the time the controller sees the value, it cannot distinguish between a value set by the user or the sanitizer (default). 

~~This PR also fixes pelias/pelias#518. `boundary.rect` parameter does not make sense for nearby and reverse. There could be a conflict if the `point.lat` and `point.lon` is outside the boundary box region. The documentation does not say `boundary.rect` is a supported parameter, so we should just give a warning.~~

### CODE REVIEW

**Comment by orangejulius** [comment]
So...story time. Long ago we had code somewhat similar to this, where we essentially overwrote raw/clean params, and thus lost knowledge of whether or not we did that or the user actually sent the param later in the code. (I actually went and found it [here](https://github.com/pelias/api/blob/2.2.1/sanitiser/_layers.js) and [here](https://github.com/pelias/api/blob/2.2.1/controller/search.js#L25)) We were eventually able to remove it, but it was fairly confusing and breaks the assumption that raw/clean all come from user entered parameters.

Is it possible instead to set the default in query/reverse if there isn't anything in clean (maybe somewhere around [here](https://github.com/pelias/api/blob/master/query/reverse.js#L84)?), and then keep raw/clean only for user input?

**Comment by tigerlily-he** [comment]
@orangejulius I agree with your concern. Adding a clean property without a raw property even is so messy and ugly. It'll be best to remove the code that overwrites `raw['boundary.circle.radius']` in the first place.

**Comment by tigerlily-he** [comment]
I think what you are saying about catching all unexpected parameters makes a lot more sense. It's much cleaner than warning for specific parameters. I can delete the second commit and work on pelias/api#279, which would resolve pelias/pelias#518.

**Comment by orangejulius** [comment]
Great, it definitely seemed to make more sense to me, I just wanted to make sure I wasn't missing something specific to the `boundary.rect` parameter. Handling all the parameters at once separately should be easier for everyone :)

**Comment by tigerlily-he** [comment]
### Update
Check for undefined `clean['boundary.circle.radius']` in `query/reverse.js` instead of trying to overwrite raw in `sanitizer/_geo_reverse.js`. 

The boundary circle radius will be undefined for coarse reverse, so just set it to the default `'1km' `from `query/reverse_defaults.js`. This value is not actually used during coarse reverse.

The check for user input of boundary circle radius in `controller/coarse_reverse.js` will work as intended (ie. it will give a warning if the user provides boundary circle radius BUT will not complain that there is a default set by the API).

Tests were updated or deleted to reflect new behavior.

File: query/reverse.js [hunk 1]
```diff
@@ -75,6 +75,18 @@ function generateQuery( clean ){
     logStr += '[param:boundary_circle] ';
   }
 
+  // for coarse reverse when boundary circle radius is undefined
+  if( check.number(clean['boundary.circle.lat']) &&
```
Comment (dianashk) [inline query/reverse.js]: Any reason not to combine this block with the one above it? Checking for lat/lon and then inside the if checking radius and setting the value accordingly?

File: query/reverse.js [hunk 2]
```diff
@@ -65,13 +65,24 @@ function generateQuery( clean ){
...
-    });
+      check.number(clean['boundary.circle.lon']) ){
+
+        vs.set({
+          'boundary:circle:lat': clean['boundary.circle.lat'],
+          'boundary:circle:lon': clean['boundary.circle.lon']
+        });
+
+        if (check.undefined(clean['boundary.circle.radius'])){
+          // for coarse reverse when boundary circle radius is undefined
```
Comment (orangejulius) [inline query/reverse.js]: this could also be the case if it's a non-coarse reverse query but the query didn't specify a boundary.circle.radius, right?

Comment (tigerlily-he) [inline query/reverse.js]: Boundary.circle.lat and boundary.circle.lon are [currently unsupported](http://pelias.github.io/compare/#/v1/reverse%3Fboundary.circle.lat=40&boundary.circle.lon=-74&point.lat=40.1&point.lon=-74.1) anyway. There shouldn't be a non-coarse reverse query that has the point coordinates without a radius.
