### PR TITLE
Details param not working as expected

### LINKED ISSUE #135: details param not working as expected
There seems to be an issue with how the details param is currently being handle in production.

My understanding is that `details` should be **off** by default and the additional fields can be enabled by passing either `?details=1` or `?details=true` in the query string.

what's currently happening in production is:

| Expected        | Actual           | Url  |
|:-------------:|:-------------:|:-----|
| off | on | http://pelias.mapzen.com/search?input=a |
| on | off | http://pelias.mapzen.com/search?input=a&details=1 |
| on | on | http://pelias.mapzen.com/search?input=a&details=true |
| off | off | http://pelias.mapzen.com/search?input=a&details=false |

The last url `details=false` is also confusing it that it disables all the `admin`/`alpha3` fields as well as those that are added when using `details=true`.

### PR DESCRIPTION
**Pull request by dianashk**
Fixes #135 

`details` can now be set to `true`, `"true"`, `1`, `"1"`, `"yes"`, `"y"` in order to receive detailed properties.

### CODE REVIEW

File: sanitiser/_details.js [hunk 1]
```diff
@@ -19,12 +19,15 @@ function sanitize( req, default_value ){
 
   if (params.details !== undefined) {
     var details = params.details;
-    
+
     if (typeof params.details === 'string') {
-      details = params.details === 'true';
```
Comment (orangejulius) [inline sanitiser/_details.js]: Is there any other code that does similar checking for "truthy"[1]? This giant conditional screams helper method to me. Its not a problem if this is the only place, but if it's not, we could do a lot to guarantee consistency in the API by making a helper method to do this sort of checking.

[1] I mean as we define truthy here, which includes 'y', 'yes', and whatever else we decide to include, not Javascripts concept of truthy

**Comment by dianashk** [comment]
Confirmed on [dev]:  

```bash
Admins-MacBook-Pro-2:acceptance-tests-clean diana$ git checkout details-flag
Admins-MacBook-Pro-2:acceptance-tests-clean diana$ node test -e dev -t dev
Tests for: http://pelias.dev.mapzen.com

GET /suggest/nearby
  ✔ [1] "{"lat":40.744243,"lon":-73.990342,"input":"DiDi dump"}"

GET /suggest/coarse
  ✔ improvement [1] "{"lat":40.744243,"lon":-73.990342,"input":"brooklyn"}"
  ✔ [2] "{"lat":40.744243,"lon":-73.990342,"input":"new york"}"
  ✔ [2] "{"lat":40.744243,"lon":-73.990342,"input":"brooklyn"}"

GET /suggest
  ✔ [1] "{"lat":40.744243,"lon":-73.990342,"input":"DiDi"}"

GET /search/coarse
  ✔ [1] "{"lat":40.744243,"lon":-73.990342,"input":"brooklyn"}"
  ✔ [2] "{"lat":40.744243,"lon":-73.990342,"input":"new york"}"

GET /search
  ✔ [1] "{"input":"brooklyn"}"
  ✔ [2] "{"input":"brooklyn, ny"}"
  ✘ [3] "{"input":"new york"}": No matching result found.
  ✔ [4] "{"input":"philadelphia"}"
  ✔ [5] "{"input":"new york, new york"}"
  ✔ [6] "{"input":"130 dean street brooklyn, ny"}"
  ✔ [7] "{"input":"billerica"}"
  ✔ [8] "{"input":"billerica, ma"}"
  ✔ [10] "{"input":"chelsea, new york"}"
  ✔ [11] "{"input":"soho, new york"}"
  ✘ [12] "{"input":"1 main st, GBR"}": No matching result found.
  ✔ [13] "{"input":"london bridge"}"
  ✔ improvement [14] "{"input":"statue of liberty"}"
  ✔ [15] "{"input":"101 saint marks pl, new york"}"
  ✘ [16] "{"input":"big ben"}": No matching result found.
  ✘ [17] "{"input":"wall street"}": No matching result found.
  ✔ [18] "{"input":"newark airport"}"
  ✔ [1425586777012:0] "{"input":"union sq"}"
  ✘ [1425586777012:1] "{"input":"union square"}": No matching result found.
  ✔ [1425586777012:2] "{"input":"portland"}"
  ✘ [1425586777012:5] "{"input":"prospect park"}": No matching result found.
  ✔ [1425586777012:6] "{"input":"london"}"

GET /reverse?categories
  ✔ [1] "{"lat":40.744243,"lon":-73.990342,"categories":"food:cuisine:chinese"}"
  ✔ [2] "{"lat":40.744243,"lon":-73.990342,"categories":"transport,transport:station"}"

GET /search
  ✔ [1] "{"layers":"admin","input":"chelsea"}"
  ✔ [2] "{"layers":"neighborhood","input":"williamsburg"}"
  ✔ [3] "{"layers":"admin","input":"ridgewood"}"

GET /*?details={false|true}
  ✔ [1] "{"input":"philadelphia","details":false}"
  ✔ [2] "{"lat":40.744243,"lon":-73.990342,"categories":"food:cuisine:chinese","details":false}"
  ✔ [3] "{"lat":40.744243,"lon":-73.990342,"input":"DiDi","details":false}"
  ✔ [4] "{"lat":40.744243,"lon":-73.990342,"input":"DiDi dump","details":false}"
  ✔ [5] "{"lat":40.744243,"lon":-73.990342,"input":"new york","details":false}"
  ✔ [6] "{"lat":40.744243,"lon":-73.990342,"input":"30 West 26th Street","details":true}"
  ✔ [7] "{"lat":40.744243,"lon":-73.990342,"input":"30 West 26th Street","details":1}"
  ✔ [8] "{"lat":40.744243,"lon":-73.990342,"input":"30 West 26th Street","details":"yes"}"
  ✔ [9] "{"lat":40.744243,"lon":-73.990342,"input":"30 West 26th Street","details":"y"}"
  ✔ [10] "{"lat":40.744243,"lon":-73.990342,"input":"30 West 26th Street","details":"no"}"

feedback app passing tests
  ✔ [1426636804303:101] "{"input":"318 19th street"}"
  ✔ [1426636804303:110] "{"input":"flatiron district"}"
  ✔ [1426636804303:113] "{"input":"101 saint marks pl"}"
  ✔ [1426636804303:114] "{"input":"flatiron building"}"
  ✔ [1426636804303:115] "{"input":"flatiron"}"
  ✔ [1426636804303:118] "{"input":"130 dean street brooklyn ny"}"
  ✔ [1426636804303:21] "{"input":"Brooklyn Museum"}"
  ✔ [1426636804303:25] "{"input":"park slope"}"
  ✔ [1426636804303:26] "{"input":"slope park"}"
  ✔ [1426636804303:27] "{"input":"jj byrne playground"}"
  ✔ [1426636804303:56] "{"input":"721 broadway"}"
  ✔ [1426636804303:60] "{"input":"madison square park"}"
  ✔ [1426636804303:61] "{"input":"madison square garden"}"
  ✔ [1426636804303:62] "{"input":"flatiron hall"}"
  ✔ [1426636804303:63] "{"input":"koreatown ny"}"
  ✔ [1426636804303:64] "{"input":"astoria park ny"}"
  ✔ [1426636804303:65] "{"input":"brooklyn bridge"}"
  ✔ [1426636804303:66] "{"input":"washington square park"}"
  ✔ [1426636804303:67] "{"input":"brooklyn bridge park"}"
  ✔ [1426636804303:68] "{"input":"manhattan bridge"}"
  ✔ [1426636804303:69] "{"input":"empire state building"}"
  ✔ [1426636804303:70] "{"input":"chrysler building"}"
  ✔ [1426636804303:71] "{"input":"rockefeller center"}"
  ✔ [1426636804303:74] "{"input":"times square"}"
  ✔ [1426636804303:75] "{"input":"11 times square"}"
  ✔ [1426636804303:76] "{"input":"bombay sandwich co"}"
  ✔ [1426636804303:77] "{"input":"flatiron building, new york"}"
  ✔ [1426636804303:79] "{"input":"momoya"}"
  ✔ [1426636804303:80] "{"input":"479 grand st"}"
  ✔ [1426636804303:81] "{"input":"69 west 9th st"}"
  ✔ [1426636804303:90] "{"input":"penn station new york"}"
  ✔ [1426636804303:93] "{"input":"astoria, queens"}"
  ✔ [1426636804303:95] "{"input":"Samsung Accelerator"}"
  ✔ [1426636804303:99] "{"input":"Ace Hotel, NYC"}"

feedback app failing tests

exact matches
  ✔ [4] "{"input":"358 41st street, ny"}"
  ✔ [6] "{"input":"1359 54 street, ny"}"
  ✔ [7] "{"input":"310 7 street, ny"}"
  ✔ [8] "{"input":"921 83 street, ny"}"
  ✔ [9] "{"input":"518 3 street, ny"}"

Verify presence of categories data.
  ✔ [1] "{"input":"East 34th Street Heliport","layers":"geoname"}"
  ✔ [2] "{"input":"Sixtyninth Regiment Armory","layers":"geoname"}"
  ✔ [3] "{"input":"Fashion Institute of Technology","layers":"geoname"}"
  ✔ [4] "{"input":"Cabrini Medical Center","layers":"geoname"}"
  ✔ [5] "{"input":"Port Authority Bus Terminal","layers":"geoname"}"
  ✔ [6] "{"input":"Manhattan Mall Shopping Center","layers":"geoname"}"
  ✔ [7] "{"input":"Cooper Station New York Post Office","layers":"geoname"}"
  ✔ [8] "{"input":"Ed Sullivan Theatre","layers":"geoname"}"
  ✔ [9] "{"input":"Glad Tidings Tabernacle Church","layers":"geoname"}"
  ✔ [10] "{"input":"National 9/11 memorial","layers":"geoname"}"
  ✔ [11] "{"input":"Weehawken Cove","layers":"geoname"}"
  ✔ [12] "{"input":"Howard Johnson Midtown Manhattan","layers":"geoname"}"
  ✔ [13] "{"input":"East River Park, ny","layers":"geoname"}"
  ✔ [14] "{"input":"Chelsea Piers","layers":"geoname"}"
  ✔ [19] "{"input":"howard winchester","layers":"osmway,osmnode,osmaddress"}"

admin lookup
  ✔ [13] "{"input":"Vista Center","layers":"neighborhood"}"
  ✔ [14] "{"input":"Yadkin Trail","layers":"neighborhood"}"
  ✔ [15] "{"input":"Hillside, Santa Clara","layers":"neighborhood"}"
  ✔ [16] "{"input":"Cardiff, GBR","layers":"admin"}"
  ✔ [17] "{"input":"ringland","layers":"neighborhood"}"
  ✔ [18] "{"input":"california","layers":"admin1"}"
  ✔ [2] "{"input":"bronx","layers":"admin2"}"
  ✔ [3] "{"input":"Lake, MT","layers":"admin2"}"
  ✔ [5] "{"lat":51.515049,"lon":-0.093229}"
  ✔ [6] "{"layers":"neighborhood","input":"hoboken"}"
  ✔ [7] "{"input":"mission, ca","layers":"admin"}"
  ✔ [8] "{"input":"crown heights","layers":"admin"}"
  ✔ [9] "{"input":"palo alto","layers":"admin"}"

address type

Aggregate test results
Pass: 105
Fail: 6
Placeholders: 0
Regressions: 0
Took 22019ms

0 regressions detected. All good.
```
